---
fabric_name: SITE2_FABRIC

# Spine Switches
spine:
  defaults:
    platform: vEOS
    loopback_ipv4_pool: 10.250.2.0/24
    bgp_as: 65200
  nodes:
    - name: dc2-spine1
      id: 1
      mgmt_ip: 192.168.0.20/24
    - name: dc2-spine2
      id: 2
      mgmt_ip: 192.168.0.21/24

# Leaf Switches
l3leaf:
  defaults:
    platform: vEOS 
    spanning_tree_priority: 4096 
    spanning_tree_mode: mstp
    loopback_ipv4_pool: 10.250.2.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.255.2.0/24
    uplink_switches:
      - dc2-spine1
      - dc2-spine2
    uplink_interfaces:
      - Ethernet2
      - Ethernet3
    uplink_ipv4_pool: 172.16.2.0/24
    mlag_interfaces:
      - Ethernet1
      - Ethernet6
    mlag_peer_ipv4_pool: 10.251.2.0/24
    mlag_peer_l3_ipv4_pool: 10.252.2.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
  node_groups:
    - group: DC2_RACK1
      bgp_as: 65201
      nodes:
        - name: dc2-leaf1
          id: 1
          mgmt_ip: 192.168.0.22/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2
        - name: dc2-leaf2
          id: 2
          mgmt_ip: 192.168.0.23/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
    # - group: DC2_RACK2
    #   bgp_as: 65202
    #   nodes:
    #     - name: dc2-leaf3
    #       id: 3
    #       mgmt_ip: 192.168.0.24/24
    #       uplink_switch_interfaces:
    #         - Ethernet4
    #         - Ethernet4
    #     - name: dc2-leaf4
    #       id: 4
    #       mgmt_ip: 192.168.0.25/24
    #       uplink_switch_interfaces:
    #         - Ethernet5
    #         - Ethernet5
    - group: DC2_BRDR
      bgp_as: 65203
      # evpn_gateway:
      #   evpn_l2:
      #     enabled: true
      #   evpn_l3:
      #     enabled: true
      #     inter_domain: true
      nodes:
        - name: dc2-brdr1
          id: 5
          mgmt_ip: 192.168.0.200/24
          uplink_switch_interfaces:
            - Ethernet7
            - Ethernet7
          # evpn_gateway:
          #   remote_peers: 
          #     - hostname: s1-brdr1
          #       bgp_as: 65103
          #       ip_address: 10.250.1.7
        - name: dc2-brdr2
          id: 6
          mgmt_ip: 192.168.0.201/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8
          # evpn_gateway:
          #   remote_peers: 
          #     - hostname: s1-brdr2
          #       bgp_as: 65103
          #       ip_address: 10.250.1.8